# $FreeBSD: src/sys/modules/re/Makefile,v 1.6 2000/01/28 11:26:34 bde Exp $

KMOD=	if_rge
SRCS=	if_rge.c if_rge_sysctl.c if_rge_stats.c if_rge_hw.c
SRCS+=	device_if.h bus_if.h pci_if.h opt_inet.h opt_inet6.h

.include <bsd.kmod.mk>
